### ISSUE TITLE
Video player - Close video/window button is missing.

### ISSUE THREAD

**Issue by oblivian** [nextcloud/files_videoplayer#33] opened 2017-06-14 07:36 UTC
### Expected behaviour
You should be able to close the video player window.

### Actual behaviour
You can't close the player window after you have started playing a video. One has to refresh the web-page to exit the video "mode". Tested with Firefox, Chrome, Edge, IE, Brave. Same result.
### Steps to reproduce
1. Upload an MP4 file.
2. Click on the video to watch.
3. Try to exit the video player...

Nextcloud 12

**Comment by tobilap** [comment] 2017-06-14 10:33
Duplicate of https://github.com/nextcloud/files_videoplayer/issues/25#issuecomment-307624508
Fix will e in 12.0.1 Release or you can add it manually

**Comment by RuudschMaHinda** [comment] 2017-06-14 10:44
If I got that right, it is one change in line 11 of the js file, right?

Did not bring the 'X' back. Took a quick look at the CSS, but that didn't show any flaws I could detect.

**Comment by enoch85** [comment] 2017-07-19 14:43
Closing as duplicate.

**Closed by enoch85** 2017-07-19 14:43 UTC
