### ISSUE TITLE
Close Icon X is missing

### ISSUE THREAD

**Issue by michag86** [nextcloud/files_videoplayer#25] opened 2017-05-03 17:31 UTC
### Expected behaviour
Bring back the close icon

### Actual behaviour
There is no close icon X. There is no way to leave the Video Player?!

### Steps to reproduce
1. Click on a Video
2. Find the Close Icon (X) :wink: 

Tested on Nextcloud 12.0 beta 1 with  Video player 1.1.0

Tested with latest Firefox and Chrome

**Comment by MorrisJobke** [comment] 2017-05-04 11:42
cc @nickvergessen @jancborchardt

**Comment by nickvergessen** [comment] 2017-05-08 09:46
Sorry, I have no idea about this app

**Comment by Instagit** [comment] 2017-05-08 13:45
The video player uses the default Nextcloud class for that:

````
.icon-view-close {
    background-image: url(../img/actions/view-close.svg?v=1);
}
````

Did something about that change in 12.0?

**Comment by michag86** [comment] 2017-05-08 14:49
JS Console shows:
ReferenceError: videojs is not defined[Weitere Informationen]  viewer.js:39:4

**Comment by schiessle** [comment] 2017-05-18 16:17
I can see it and reproduce it but my JS knowledge is to limited to debug/fix it... cc @nextcloud/javascript

**Comment by schiessle** [comment] 2017-05-19 13:40
Git bisect told me that this is the commit which finally broke it: https://github.com/nextcloud/files_videoplayer/commit/77c215226cbb05e81866239913a43fb2d1b6f8b6

Note: Even before this commit the close button is not visible, but at least it was possible to close the video player by clicking outside of the video. @icewind1991 can you have a look? Thanks!

**Comment by tobilap** [comment] 2017-05-20 16:08
I'm not a pro in JS but I just debugged it and made a fix:
https://github.com/nextcloud/files_videoplayer/commit/37c2866e319e0e8ff1b2f70da3a1d8c7cd21697b
Can someone check if its "good practice"?

**Comment by brantje** [comment] 2017-05-20 22:02
Not really an JS expert, but `eval` = evil as far i can remember.

**Comment by tobilap** [comment] 2017-05-20 22:06
We want to execute the JS File anyway so this might  be the right choice here. Before it was just loaded but not evaluated and thats why the error happened.

**Comment by MorrisJobke** [comment] 2017-05-20 22:10
> I'm not a pro in JS but I just debugged it and made a fix:

cc @LukasReschke another problem with the disabled eval.

**Comment by LukasReschke** [comment] 2017-05-21 16:30
The `eval` here is the right thing to do as that's what  `$.getScript` also seems to call but we disabled that in March with https://statuscode.ch/2017/03/CSP-unsafe-eval-and-jquery/. Can you do a pull request?

**Comment by Instagit** [comment] 2017-05-26 09:06
@himbeere You only saw the playback time, because VideoJS failed to load and the default HTML5 video player was used instead. I'm working (slowly) on a [replacement for the video player](https://github.com/nextcloud/files_videoplayer/issues/20) that shows the playback time and adds more features.

**Comment by himbeere** [comment] 2017-05-26 09:12
Ah, good to know. Thanks for the heads up.

**Comment by DDArn** [comment] 2017-06-11 10:47
Hello
still no solution on the (X) in video player.
I moved back to nextcloud 11.0.3 and there is no problem at all
This is a bug in nextcloud12.0.0?

**Comment by tobilap** [comment] 2017-06-11 11:55
There is a fix and its already in the release for 12.0.1 which will probably be released by the end of June.
Just add the fix manually to your nextcloud installation.
https://github.com/nextcloud/files_videoplayer/commit/37c2866e319e0e8ff1b2f70da3a1d8c7cd21697b

**Comment by elpraga** [comment] 2017-06-11 14:57
Thank you for releasing the manual fix! After applying, Ctrl+F5 to reload the page has to be used to see the effect.

Adding total time and time elapsed would be great!

**Comment by oeves** [comment] 2017-07-11 14:49
I had the same issue, seems to be Fixed in Safari & Firefox (37c2866).
But Chrome (macOS) doesn't show the X, looks like it uses a different player.

**Comment by gemlog** [comment] 2017-08-06 20:46
Thank you for the fix. I just applied it in my syncloud virtual box install. Works great in FF. 

I'd just like to mention that it would be nice if someone could take the time to copy it into the demo instance? That bug was a bit off-putting for me. Obviously, I installed it anyhow, but for other people it might be a show-stopper.

**Comment by sebastienhuynen** [comment] 2017-08-06 20:50
thanks you resolve my problem. It's fixed on firefox et ie on windows phone :)

**Comment by lraty** [comment] 2017-11-21 20:47
I tried Nextcloud demo from Nextcloud web page. I didn't find any way to close video. Arch Linux, Firefox, UltraHD resolution. Also confirmed in Chrome.

**Comment by Instagit** [comment] 2017-11-22 08:39
Thanks for this. The video player is not loaded correctly. I'll forward this.

````
Uncaught ReferenceError: videojs is not defined
````

**Comment by jancborchardt** [comment] 2018-11-20 15:38
This is occuring again on the latest master:

> ReferenceError: videojs is not defined[Learn More] viewer.js:45:4 

Any idea @Instagit @nextcloud/javascript? It makes it impossible to close videos, you have to manually refresh the video. cc @karlitschek

**Comment by juliushaertl** [comment] 2018-11-20 15:43
Seems this is caused by the stricter CSP, which blocks the eval that is used to load the player: https://github.com/nextcloud/files_videoplayer/blob/master/js/viewer.js#L11

**Comment by rullzer** [comment] 2018-11-20 16:36
Are we sure it is the csp? Because I can play videos just fine. I'll debug this evening.

**Comment by rullzer** [comment] 2018-11-20 20:08
Fix for the CSP in https://github.com/nextcloud/files_videoplayer/pull/67

**Closed** 2018-11-21 09:14 UTC
Labels: bug, regression
