### ISSUE TITLE
Video bigger than 2GB are stop at 2GB

### ISSUE THREAD

**Issue by einhorn21** [nextcloud/files_videoplayer#39] opened 2017-08-28 09:56 UTC
### Expected behaviour
My uploaded 3.2GB file should play succesfull in the web GUI

### Actual behaviour
It plays and stops at ~2/3 (~2GB) with the error “The video playback was aborted due to a corruption problem or because the video used features your browser did not support.”

Nextcloud log in Admin > Logging:
Error PHP	fseek() expects parameter 2 to be integer, string given at /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php#177

### Steps to reproduce
1. Install nextcloud on a raspberry pi 3 (ubuntu mate)
2. upload a video file bigger than 2GB
3. watch it. (it will only play to the moment where its reach the 2GB)

**Comment by Instagit** [comment] 2017-08-28 15:42
Thanks for reporting this.

>it will only play to the moment where its reach the 2GB

Can you skip the video to a specific time to reproduce this or does it really depend on how much data was streamed? Have you verified the video was completely uploaded?

**Comment by einhorn21** [comment] 2017-08-28 21:34
Yes when i skip to the end (for example to 2.5hours of 3 hours) it stops.

and when i download it, i can play the whole video on my pc... 

can it be that nextcloud can read only the first 2GB?

also there is this 2GB limitation thing on 32bit devices... (you cant upload >2GB files over the web GUI)

**Comment by einhorn21** [comment] 2017-08-28 21:46
maybe "fseek() expects parameter 2 to be integer" this could be the answer... 
doesnt have integer a Range of values from -2,147,483,647 to +2,147,483,647? (2,147,483,647 = my ~2GB?)

**Comment by Instagit** [comment] 2017-08-29 09:55
I tried with a 4.5 GB video and that works fine for me. I can skip to the end without problems.

It looks like hitting PHP integer limits could really be the cause here. Since this isn't a problem with the video player and I don't know how to help with it, I'll open an issue at https://github.com/nextcloud/server/issues.

**Comment by einhorn21** [comment] 2017-08-30 09:46
what hardware do you have?

**Comment by Instagit** [comment] 2018-10-12 14:29
This seemed like more of a hardware / operating system problem, so I'm closing it for now.

If you still have this problem: What operating system and PHP version are you using?

**Closed by Instagit** 2018-10-12 14:29 UTC
