### ISSUE TITLE
X on top right corner is not showing

### ISSUE THREAD

**Issue by Chriss78** [nextcloud/files_videoplayer#31] opened 2017-06-02 11:52 UTC
### Expected behaviour
The Windowed Video should close.

### Actual behaviour
The Window stays open. Only way to cloase it is to reload the page.

### Steps to reproduce
1. Click a video File from the Files tab. Video is playing but cannot be closed.
Nextclod 12.0.0

**Comment by devz3r0** [comment] 2017-06-03 10:31
I rechecked that in my nc 12 release version too, I have the same issue.

**Comment by enoch85** [comment] 2017-06-03 11:07
cc @nickvergessen

**Comment by nickvergessen** [comment] 2017-06-06 10:14
12.0.1 + https://github.com/nextcloud/files_videoplayer/commit/37c2866e319e0e8ff1b2f70da3a1d8c7cd21697b make it work.

Will backport the fix

**Comment by nickvergessen** [comment] 2017-06-06 10:16
Duplicate of #30 

PR in #32

**Comment by enoch85** [comment] 2017-06-06 11:08
So this can be closed.

**Closed by enoch85** 2017-06-06 11:08 UTC
Labels: bug
